### PR TITLE
Fix for the CLI client

### LINKED ISSUE #1409: [Bug] : identity used in various places in cli and mls-ds not always the same
**Describe the bug**
After inviting a client into a group from another cli, calling update in the invited client cli leads to a crash

**To Reproduce**
1. launch mls-ds
2. launch a first cli
3. in the first cli register a client "alice": register alice
4. create a group "GR1": create group GR1
5. launch a second cli
6. in the second cli register a client "bob": register bob
7. in this first cli call update
8. in this first cli invite bob in group GR1: group GR1> invite bob
9. See error "thread 'main' panicked at 'There's a member in the group we don't know.', cli/src/user.rs:92:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

**Expected behavior**
bob is invited in alice's GR1 group and they are able to send messages to each other

**Actual behavior**
the cli crashes

**Platform (please complete the following information):**
- Linux Ubuntu 22.04.2 x86_64

### PR DESCRIPTION
**Pull request by Firefly35**
fix: align the source of "identity" in User struct in the various methods with delivery service ClientInfo struct

### CODE REVIEW

**Comment by raphaelrobert** [comment]
@Firefly35 You flagged this for review, but the CI is not passing yet

**Comment by Firefly35** [comment]
Indeed, but I don't get what is going wrong about format check ?

**Comment by raphaelrobert** [comment]
This will have to be rebased on #1413 for the tests to pass.

**Comment by Firefly35** [comment]
Rebase is made.

**Review by raphaelrobert — APPROVED** [review]
Thanks for the PR!

Going forward please use more descriptive titles.

**Comment by Firefly35** [comment]
Sure I will do

**Pull request merged**
