### PR TITLE
Fix CI: Forcing CI to always checkout the HEAD commit

### PR DESCRIPTION
**Pull request by raphaelrobert**
Fixing this issue: https://github.com/actions/checkout/issues/299

### CODE REVIEW

**Review by franziskuskiefer — COMMENTED** [review]
Hm, but this only works for PRs, not pushes to main.

**Comment by raphaelrobert** [comment]
> Hm, but this only works for PRs, not pushes to main.

Were do we fix that?

**Comment by franziskuskiefer** [comment]
Well, we could use the appropriate hash each time. But that probably ends up being pretty ugly. Some other comments say v1 might work (not sure if we need anything that's v2 specific)

**Comment by raphaelrobert** [comment]
Why don't we try this? If it doesn't work we can always change later.

**Comment by franziskuskiefer** [comment]
> Why don't we try this? If it doesn't work we can always change later.

do it!

**Comment by raphaelrobert** [comment]
Can you approve? :) It will auto-merge.

**Review by franziskuskiefer — APPROVED** [review]

**Pull request merged**
