### PR TITLE
Duesee/make interop work 1

### PR DESCRIPTION
**Pull request by duesee**
This PR introduces some fixes in OpenMLS to interop with other implementations. There is one test failing and I can't really trace down what the cause is. At some point Bob and the Public Group disagree about the confirmed_transcript_hash (`b''`) for public group, something for Bob. But I'm a bit puzzled about this because it appears to me that `b''` is correct. But this would mean Bob or Alice do something wrong, which would mean that interop shouldn't work. I'll need some more time (and better tracing) to figure this out.

### CODE REVIEW

**Comment by franziskuskiefer** [comment]
> At some point Bob and the Public Group disagree about the confirmed_transcript_hash (`b''`) for public group, something for Bob. But I'm a bit puzzled about this because it appears to me that `b''` is correct.

The transcript hash is only empty in epoch 0. The error appears to occur later and the public group is not updating it's group context correctly.

**Comment by duesee** [comment]
> The transcript hash is only empty in epoch 0. The error appears to occur later and the public group is not updating it's group context correctly.

Do you have time to take a fresh look on it? Maybe I'm just overlooking somehting. In the meantime I could continue to work on `duesee/make_interop_work_2`. When we get these things merged, OpenMLS would almost interoperate on all scenarios.

**Review by franziskuskiefer — COMMENTED** [review]
Looks like we need for this.
Reverting the changes in `staged_commit.rs` and `group_info.rs` makes thing work again and I'm not sure these changes are correct.
So we need a test that requires these changes here to go through to figure out why/if they are needed.

**Review by franziskuskiefer — APPROVED** [review]
Thanks, let's get this in

**Pull request merged**
