### PR TITLE
Some more benchmarks

### LINKED ISSUE #1596: OpenMLS Benchmarks
Adding some more benchmarking for OpenMLS.
This especially adds some infrastructure to benchmark larger groups.

https://github.com/openmls/openmls/compare/main...franziskus/large-group-benchmarks

### PR DESCRIPTION
**Pull request by franziskuskiefer**
This PR adds facilities to run benchmarks on larger groups.

Design
- not criterion based
- ability read/write group state into files for testing larger groups
- different group setups
- cli interface to quickly test different scenarios

This required a few small changes to OpenMLS library code to derive some more `Clone`s for testing (benchmarking). Also, the memory key store can be written to files now.

Closes #1596

### CODE REVIEW

**Review by raphaelrobert — CHANGES_REQUESTED** [review]
Thanks, we really need more benchmarks. We probably don't need an in-depth code review here but I do have some high-level questions and remarks:

 - Why not use criterion? Measuring is hard and using something like criterion would at least make us avoid basic mistakes.
 - Since it's a benchmark, why not have it in the `benches` folder? I think we should reserve the `examples` folder for actual examples. Benchmarks can also read command line arguments, if that's your worry.
  - This needs some high-level documentation. It's hard (if not impossible) to understand what the command line arguments are for. It's also not really obvious what exactly is being measured. I'm worried it's hard for others to maintain this code.
  - This should run on the CI to ensure it doesn't become stale when the library is refactored. I suspect this could be run with small values so that the CI doesn't take forever but still covers all relevant code paths.

**Comment by franziskuskiefer** [comment]
> * Why not use criterion? Measuring is hard and using something like criterion would at least make us avoid basic mistakes.

The memory overhead from criterion is way too high unfortunately. We'd only measure memcpy.

> * Since it's a benchmark, why not have it in the `benches` folder? I think we should reserve the `examples` folder for actual examples. Benchmarks can also read command line arguments, if that's your worry.

They can, but you can't run them in the same way through cargo, so you'd need to build them separately. If there's a way around that, I'm happy to move them to benches.

> * This needs some high-level documentation. It's hard (if not impossible) to understand what the command line arguments are for. It's also not really obvious what exactly is being measured. I'm worried it's hard for others to maintain this code.

I can add some comments. The help text on the cli should have all information for using it though.

> * This should run on the CI to ensure it doesn't become stale when the library is refactored. I suspect this could be run with small values so that the CI doesn't take forever but still covers all relevant code paths.

Right, I'll put on CI.

**Comment by raphaelrobert** [comment]
> > * Since it's a benchmark, why not have it in the `benches` folder? I think we should reserve the `examples` folder for actual examples. Benchmarks can also read command line arguments, if that's your worry.
> 
> They can, but you can't run them in the same way through cargo, so you'd need to build them separately. If there's a way around that, I'm happy to move them to benches.

I looked into this. Passing command line arguments also works with `cargo bench`, but it's somewhat limited because they can conflict with `libtest`. You would have to resort to using env variables instead or something like that.

> > * This needs some high-level documentation. It's hard (if not impossible) to understand what the command line arguments are for. It's also not really obvious what exactly is being measured. I'm worried it's hard for others to maintain this code.
> 
> I can add some comments. The help text on the cli should have all information for using it though.

I didn't find any explanation for what [these parameters](https://github.com/openmls/openmls/pull/1600/files#diff-e861fc216d637d56ee3f00494a1a01a925ff12dd1d67c497a8067f61ef8c458dR390-R402) do exactly.

**Comment by franziskuskiefer** [comment]
> You would have to resort to using env variables instead or something like that.

Right, that's why I moved it over. I think it's nicer to have a proper tool.

I added usage infos and a CI job.

**Review by raphaelrobert — APPROVED** [review]
Thanks, let's get this in!

**Pull request merged**
