### PR TITLE
Remove max_past_epochs field from MlsGroupBuilder

### PR DESCRIPTION
**Pull request by kkohbrok**
Fixes the issue raised in #1660.

This PR removes the `max_past_epochs` field from the builder, which is erroneously read instead of the field from the group create config. There was already no way to set it, so removing it only restores the expected behaviour of applications being able to set the `max_past_epochs` via the group create config.

### CODE REVIEW

**Comment by franziskuskiefer** [comment]
This should be covered in #1661. Do you not like the solution there?

**Comment by kkohbrok** [comment]
Sorry, I should really have commented in #1661.

The solution in #1661 is to set the `max_past_epochs` value in the builder to the value in the config, which is then used during group creation. However, we can just remove that middle-variable and use the variable in the config during group creation. The middle variable (i.e. the one in the builder) isn't really used anywhere else and (as pointed out in #1660) is never even set.

**Comment by keks** [comment]
I think this can be closed, since I included in in #1661.

**Comment by kkohbrok** [comment]
Closing, because this was included in #1661.

**Pull request closed without merging**
