### PR TITLE
refactor trait openmls traits

### PR DESCRIPTION
**Pull request by jbis9051**
Adds specificity to parameters of methods that exclusively use MLS traits

### CODE REVIEW

**Comment by jbis9051** [comment]
Fixes #1389

**Comment by jbis9051** [comment]
If I didn't miss anything, all functions should use the most specific trait they can. There's are build errors for all functions that use more than one trait, this is intentional. I will resolve this once I get a response for https://github.com/openmls/openmls/issues/1389#issuecomment-1591884894.

**Comment by jbis9051** [comment]
Forgot to fix the tests, will do

**Comment by raphaelrobert** [comment]
@jbis9051 You requested a review, but there are merge conflicts that need to be resolved

**Comment by jbis9051** [comment]
@raphaelrobert Fixed

**Comment by jbis9051** [comment]
@raphaelrobert Formatted

**Review by raphaelrobert — CHANGES_REQUESTED** [review]
Thank you for tackling this rather daunting task!
It looks fine to me in general. For consistency, could you also rename the `backend` variables/parameters to `provider`?

Note also that because of the API changes, we'll only merge this after the v0.5 release, which should happen soon.

**Comment by jbis9051** [comment]
Looks like v0.5 was merged. I'll make the requested changes soon.

**Comment by jbis9051** [comment]
@raphaelrobert How's that?

**Comment by raphaelrobert** [comment]
> @raphaelrobert How's that?

Thanks, the format check is unhappy, you need to run `cargo fmt`.

**Review by raphaelrobert — APPROVED** [review]
Thanks for making all the changes, let's get this in.

**Pull request merged**
