### PR TITLE
ci: Fix coverage job.

### PR DESCRIPTION
**Pull request by duesee**
~I couldn't find a "timeout" in GitHub actions but assumed it should mean "seconds". Minutes would exceed the default `timeout-minutes: 360`, which is likely not what we want. Given that 500 seconds are roughly 10 minutes and the job is taking longer, I removed the timeout altogether. The added `version` should fix the rest. Not sure why there was a `cargo clean` but it doesn't seem necessary.~

This PR switches the coverage measurement from tarpaulin to grcov.

### CODE REVIEW

**Comment by duesee** [comment]
Despite the failing test here due to the `pull_request_target` context, measurement with grcov seems to work. See https://github.com/openmls/openmls/actions/runs/4014259323/jobs/6894556999, and https://app.codecov.io/github/openmls/openmls/commit/6798965a96ff858753fda4214f07555f4f5a26df.

**Review by franziskuskiefer — CHANGES_REQUESTED** [review]
The actions you use here (`cargo` and `grcov`) don't appear to be maintained. So it's not really an improvement, other than that it works for now.
Let's do this properly.

**Comment by duesee** [comment]
> So it's not really an improvement, other than that it works for now.

Unblocking the PR workflow sounds like an improvement to me... Anyway, we could execute the required grcov steps manually. Would that suffice or do you have something specific in mind?

**Review by franziskuskiefer — APPROVED** [review]
yeah, you're right. Let's get this in but leave the issue open to do the steps manually so we don't run into the same issues again when the actions break.

**Pull request merged**
