### PR TITLE
Remove tree rewrite chapter from book

### PR DESCRIPTION
**Pull request by kkohbrok**
I've also removed the corresponding pages from the wiki.

### CODE REVIEW

**Review by raphaelrobert — CHANGES_REQUESTED** [review]
Thanks, you should also remove the entry from the summary

**Comment by kkohbrok** [comment]
I was under the impression that that happens automatically with mdBook.

**Comment by raphaelrobert** [comment]
> I was under the impression that that happens automatically with mdBook.

We have a `SUMMARY.md` file that still has that entry though.

**Review by raphaelrobert — APPROVED** [review]
Thanks!

**Pull request merged**
