### PR TITLE
use byte slice for key store key

### LINKED ISSUE #656: Key store - key bound
There have been concerns about the trait bound for the key values in the kay store.
Right now keys have to implement `Hash`.
https://github.com/openmls/openmls/blob/e9b65c651c56f101cff7d773717e261a3d74ef36/traits/src/key_store.rs#L25

One option would be to take a byte slice `k: &[u8]` instead. I think this would work. It might not improve performance though because the key might be a serialisation of a struct. But right now I think most keys can be cheaply converted to byte slices.

@OtaK thoughts or comments?

### PR DESCRIPTION
**Pull request by franziskuskiefer**
Note that the memory key store simply uses the provided bytes as key.
This is not recommended for production systems as this might get
large.

fixes #656

### CODE REVIEW

**Review by raphaelrobert — COMMENTED** [review]
Thanks, the changes look rather straightforward. Can we use this PR to also add some documentation in the book on how to use the key store?

**Comment by franziskuskiefer** [comment]
> Can we use this PR to also add some documentation in the book on how to use the key store?

I can open another PR for that. I don't want to pollute this with unrelated content.

**Comment by franziskuskiefer** [comment]
See #750

**Review by raphaelrobert — APPROVED** [review]
Thanks!

**Pull request merged**
