### PR TITLE
Proc macro to test all ciphersuites

### PR DESCRIPTION
**Pull request by franziskuskiefer**
This PR adds a new crate `test_macros` that exposes a proc-macro
`ctest` that allows defining tests for all supported ciphersuites
as follows

```
ctest!(test_name {
  // test body
})
```

This is used to replace the existing tests in tests/test-key_packages.rs

### CODE REVIEW

**Review by kkohbrok — DISMISSED** [review]
This looks pretty cool! I'll try it out in the decryption index test.

**Comment by raphaelrobert** [comment]
I like the idea! I'm just concerned this might throw off `rust-analyzer` and `cargo check/clippy`. I can test this in a bit if it hasn't already be done.

**Comment by kkohbrok** [comment]
I also sometimes get tooling issues when working with macros. Autocomplete won't work properly and clippy gets confused. But for development, we can always copy the code out and convert it to a macro afterwards.

**Comment by franziskuskiefer** [comment]
These tools aren't perfect and can't handle the entirety of Rust unfortunately. But you also shouldn't rely too much on them 😉

**Review by kkohbrok — APPROVED** [review]
Looks good! Looking forward to using this for the interop test scenarios!

**Pull request merged**
