### PR TITLE
Remove stale tests

### PR DESCRIPTION
**Pull request by raphaelrobert**
Removes stale tests decommissioned during the tree rewrite a year ago but never deleted.

### CODE REVIEW

**Review by franziskuskiefer — COMMENTED** [review]
Thanks, just two questions
- The treemath kat we might want to have for the treesync module?
- Do we have enough tests on the treesync module or would it make sense to move some of the unit tests there?

**Comment by raphaelrobert** [comment]
> Thanks, just two questions
> 
>     * The treemath kat we might want to have for the treesync module?

The treemath KAT was there twice. I deleted the stale and unused one.

>     * Do we have enough tests on the treesync module or would it make sense to move some of the unit tests there?

These tests seem to be very specific to the old code structure. Since treesync has a completely different API, they are pretty worthless.

**Review by franziskuskiefer — DISMISSED** [review]
👍🏻 :shipit:

**Comment by raphaelrobert** [comment]
I had to address merge conflicts.

**Review by franziskuskiefer — APPROVED** [review]

**Pull request merged**
