### PR TITLE
Make composite types 2^32 and make 0 invalid for enums

### LINKED ISSUE #61: Make composite types 2^32 and make 0 invalid for enums (#387)
https://github.com/mlswg/mls-protocol/pull/387

### PR DESCRIPTION
**Pull request by raphaelrobert**
Fixes #61.

Note that this does not yet address #186, in fact I had to deactivate some more code and I mentioned this in TODOs in several places.

### CODE REVIEW

**Comment by kkohbrok** [comment]
I've only skimmed over the changes, but this PR doesn't just make composite types 2^32. It also changes a few other things. For example, a `signature_scheme` function is added to `impl Credential` and new things seem to be included in the `GroupContext`. If you're doing more than just fix #61, it would be nice if you could give a rough summary of what this PR is doing so I/we know what to look out for.

**Comment by raphaelrobert** [comment]
> I've only skimmed over the changes, but this PR doesn't just make composite types 2^32. It also changes a few other things. For example, a `signature_scheme` function is added to `impl Credential` and new things seem to be included in the `GroupContext`. If you're doing more than just fix #61, it would be nice if you could give a rough summary of what this PR is doing so I/we know what to look out for.

Yeah, sorry, looks like some bits from #324 made it into here. That should disappear once #324 is merged.

**Review by kkohbrok — APPROVED** [review]
I'm still not sure why `GroupContext` needs a new field to address #61, but it probably needs to be done anyway. Other than that, it looks good!

**Comment by raphaelrobert** [comment]
> I'm still not sure why `GroupContext` needs a new field to address #61, but it probably needs to be done anyway. Other than that, it looks good!

Because it was missing the `extensions` field altogether. #61 was about changing how that field is encoded.

**Comment by kkohbrok** [comment]
> > I'm still not sure why `GroupContext` needs a new field to address #61, but it probably needs to be done anyway. Other than that, it looks good!
> 
> Because it was missing the `extensions` field altogether. #61 was about changing how that field is encoded.

Ah, sorry, I had overlooked that. That makes total sense, then.

**Pull request merged**
